# Done to increase the memory available to gradle.
org.gradle.jvmargs=-Xmx1G
org.gradle.parallel=true
org.gradle.configuration-cache=false

# Fabric Properties
# check these on https://fabricmc.net/develop
minecraft_version=26.1.2
minecraft_compatibility=26.1.x
release_game_versions=26.1,26.1.1,26.1.2
loader_version=0.19.3
loom_version=1.17-SNAPSHOT

# Mod Properties
mod_version=1.1.0
maven_group=com.xurify.elytraassistant
archives_base_name=elytraassistant
modding_api=fabric

# Dependencies
fabric_api_version=0.155.2+26.1.2
# https://modrinth.com/mod/fabric-api/versions
modmenu_version=18.0.0
cloth_config_version=26.1.154

# gradlew migrateMappings --mappings "1.21.1+build.3"
